package com.hubspot.boomslang;

import com.dylibso.chicory.runtime.HostFunction;

/**
 * A named bundle of WASM host functions that a Python runtime build imports. Register extensions
 * via {@link PythonExecutorFactory.Builder#addExtension(BoomslangExtension)}; the bundled runtime
 * requires the built-in {@link HostBridge} extension. Custom typed extensions are generated by
 * boomslang-hostgen and composed into a custom host build.
 */
public interface BoomslangExtension {
  /** Returns the extension's name, matching the extension declared in the host build. */
  String name();

  /** Returns the WASM host functions this extension contributes. */
  HostFunction[] hostFunctions();
}
