use heck::{ToLowerCamelCase, ToUpperCamelCase};
use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
pub struct Manifest {
    pub extension: Extension,
    #[serde(default)]
    pub functions: Vec<Function>,
}

#[derive(Deserialize)]
pub struct Extension {
    pub name: String,
    pub wasm_module: Option<String>,
    #[serde(default)]
    pub prewarm: Vec<String>,
}

#[derive(Deserialize)]
pub struct Function {
    pub name: String,
    #[serde(default)]
    pub params: Vec<Param>,
    #[serde(default)]
    pub returns: Option<String>,
}

#[derive(Deserialize)]
pub struct Param {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: String,
}

pub fn parse_manifest(path: &Path) -> Manifest {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    toml::from_str(&content)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", path.display(), e))
}

/// Call from your extension crate's build.rs.
/// Reads extension.toml from the crate root and writes generated Rust to OUT_DIR.
///
/// ```rust,ignore
/// // build.rs
/// fn main() {
///     boomslang_hostgen::generate_rust("extension.toml");
/// }
/// ```
pub fn generate_rust(manifest_path: &str) {
    let manifest_path = Path::new(manifest_path);
    let manifest = parse_manifest(manifest_path);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set (are you in a build.rs?)");
    let filename = format!("ext_{}.rs", manifest.extension.name);
    let code = generate_rust_code(&manifest);
    fs::write(Path::new(&out_dir).join(&filename), code).unwrap();

    println!("cargo:rerun-if-changed={}", manifest_path.display());
}

/// Generate Java host function bindings to a directory.
pub fn generate_java(manifest_path: &str, out_dir: &str, package: &str) {
    let manifest = parse_manifest(Path::new(manifest_path));
    let package_dir = Path::new(out_dir).join(package.replace('.', "/"));
    fs::create_dir_all(&package_dir).unwrap();
    let code = generate_java_code(&manifest, package);
    let classname = format!(
        "{}HostFunctions",
        manifest.extension.name.to_upper_camel_case()
    );
    fs::write(package_dir.join(format!("{}.java", classname)), code).unwrap();
}

// ── Rust codegen ──────────────────────────────────────────────

pub fn generate_rust_code(m: &Manifest) -> String {
    let mod_name = &m.extension.name;
    let wasm_mod = m.extension.wasm_module.as_deref().unwrap_or(mod_name);

    let mut out = String::new();
    out.push_str("use pyo3::prelude::*;\n\n");

    // WASM import declarations
    out.push_str(&format!(
        "#[link(wasm_import_module = \"{}\")]\n",
        wasm_mod
    ));
    out.push_str("unsafe extern \"C\" {\n");
    for f in &m.functions {
        out.push_str(&format!("    fn {}(\n", wasm_import_name(f)));
        for p in &f.params {
            for (wn, wt) in wasm_params(&p.name, &p.ty) {
                out.push_str(&format!("        {}: {},\n", wn, wt));
            }
        }
        if f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes") {
            out.push_str("        result_ptr: *mut u8,\n");
            out.push_str("        result_max_len: i32,\n");
        }
        let ret = wasm_return_type(f.returns.as_deref());
        out.push_str(&format!("    ) -> {};\n", ret));
    }
    out.push_str("}\n\n");

    out.push_str("const MAX_RESULT: i32 = 1024 * 1024;\n\n");

    // PyO3 wrapper functions
    for f in &m.functions {
        out.push_str(&generate_rust_pyo3_wrapper(f));
        out.push_str("\n");
    }

    // Forward-declare the PyInit function generated by #[pymodule]
    let py_mod_name = format!("_{}", mod_name);
    out.push_str(&format!(
        "unsafe extern \"C\" {{\n    #[allow(non_snake_case)]\n    fn PyInit_{}() -> *mut pyo3::ffi::PyObject;\n}}\n\n",
        py_mod_name
    ));

    // Module registration
    out.push_str(&format!(
        "pub fn register() {{\n    unsafe {{\n        pyo3::ffi::PyImport_AppendInittab(\n            b\"{}\\0\".as_ptr() as *const i8,\n            Some(PyInit_{}),\n        );\n    }}\n}}\n\n",
        py_mod_name, py_mod_name
    ));

    out.push_str(&format!(
        "pub fn prewarm(py: Python) {{\n    let modules = {:?};\n    for name in modules {{\n        match py.import(name) {{\n            Ok(_) => eprintln!(\"[prewarm] OK: {{}}\", name),\n            Err(e) => eprintln!(\"[prewarm] FAILED: {{}} - {{:?}}\", name, e),\n        }}\n    }}\n}}\n\n",
        m.extension.prewarm
    ));

    // #[pymodule]
    out.push_str(&format!(
        "#[pymodule]\nfn {}(m: &Bound<'_, PyModule>) -> PyResult<()> {{\n",
        py_mod_name
    ));
    for f in &m.functions {
        out.push_str(&format!(
            "    m.add_function(wrap_pyfunction!(py_{}, m)?)?;\n",
            f.name
        ));
    }
    out.push_str("    Ok(())\n}\n");

    out
}

fn generate_rust_pyo3_wrapper(f: &Function) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "#[pyfunction]\n#[pyo3(name = \"{}\")]\n",
        f.name
    ));
    let ret_type = match f.returns.as_deref() {
        Some("string") => "PyResult<String>",
        Some("int") => "PyResult<i32>",
        Some("float") => "PyResult<f64>",
        Some("bytes") => "PyResult<Vec<u8>>",
        None => "PyResult<()>",
        _ => "PyResult<String>",
    };
    out.push_str(&format!("fn py_{}(", f.name));
    let py_params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", &p.name, rust_py_type(&p.ty)))
        .collect();
    out.push_str(&py_params.join(", "));
    out.push_str(&format!(") -> {} {{\n", ret_type));
    out.push_str("    unsafe {\n");

    for p in &f.params {
        if p.ty == "string" {
            out.push_str(&format!(
                "        let {name}_bytes = {name}.as_bytes();\n",
                name = p.name
            ));
        } else if p.ty == "bytes" {
            out.push_str(&format!(
                "        let {name}_bytes = {name};\n",
                name = p.name
            ));
        }
    }

    if f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes") {
        out.push_str("        let mut result_buf = vec![0u8; MAX_RESULT as usize];\n");
    }

    if f.returns.is_some() {
        out.push_str(&format!("        let ret = {}(\n", wasm_import_name(f)));
    } else {
        out.push_str(&format!("        {}(\n", wasm_import_name(f)));
    }
    for p in &f.params {
        match p.ty.as_str() {
            "string" | "bytes" => {
                out.push_str(&format!(
                    "            {name}_bytes.as_ptr(),\n            {name}_bytes.len() as i32,\n",
                    name = p.name
                ));
            }
            "int" | "float" => {
                out.push_str(&format!("            {},\n", p.name));
            }
            _ => {}
        }
    }
    if f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes") {
        out.push_str("            result_buf.as_mut_ptr(),\n");
        out.push_str("            MAX_RESULT,\n");
    }
    out.push_str("        );\n");

    match f.returns.as_deref() {
        Some("string") => {
            out.push_str("        if ret < 0 {\n");
            out.push_str("            return Err(PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(\"host call failed\"));\n");
            out.push_str("        }\n");
            out.push_str("        Ok(String::from_utf8_lossy(&result_buf[..ret as usize]).into_owned())\n");
        }
        Some("bytes") => {
            out.push_str("        if ret < 0 {\n");
            out.push_str("            return Err(PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(\"host call failed\"));\n");
            out.push_str("        }\n");
            out.push_str("        Ok(result_buf[..ret as usize].to_vec())\n");
        }
        Some("int") => out.push_str("        Ok(ret)\n"),
        None => out.push_str("        Ok(())\n"),
        _ => out.push_str("        Ok(ret)\n"),
    }

    out.push_str("    }\n}\n");
    out
}

fn wasm_import_name(f: &Function) -> String {
    f.name.clone()
}

fn wasm_params(name: &str, ty: &str) -> Vec<(String, &'static str)> {
    match ty {
        "string" | "bytes" => vec![
            (format!("{}_ptr", name), "*const u8"),
            (format!("{}_len", name), "i32"),
        ],
        "int" => vec![(name.to_string(), "i32")],
        "float" => vec![(name.to_string(), "f64")],
        _ => vec![(name.to_string(), "i32")],
    }
}

fn wasm_return_type(ty: Option<&str>) -> &'static str {
    match ty {
        Some("string") | Some("bytes") | Some("int") => "i32",
        Some("float") => "f64",
        None => "()",
        _ => "i32",
    }
}

fn rust_py_type(ty: &str) -> &'static str {
    match ty {
        "string" => "&str",
        "int" => "i32",
        "float" => "f64",
        "bytes" => "&[u8]",
        _ => "&str",
    }
}

// ── Java codegen ──────────────────────────────────────────────

pub fn generate_java_code(m: &Manifest, package: &str) -> String {
    let ext_name = &m.extension.name;
    let class_name = format!("{}HostFunctions", ext_name.to_upper_camel_case());
    let wasm_mod = m.extension.wasm_module.as_deref().unwrap_or(ext_name);

    let mut out = String::new();
    out.push_str(&format!("package {};\n\n", package));
    out.push_str("import com.dylibso.chicory.runtime.HostFunction;\n");
    out.push_str("import com.dylibso.chicory.runtime.Instance;\n");
    out.push_str("import com.dylibso.chicory.runtime.Memory;\n");
    out.push_str("import com.dylibso.chicory.wasm.types.ValueType;\n");
    out.push_str("import java.nio.charset.StandardCharsets;\n");
    out.push_str("import java.util.ArrayList;\n");
    out.push_str("import java.util.List;\n\n");

    out.push_str(&format!("public class {} {{\n\n", class_name));
    out.push_str(&format!(
        "  private static final String MODULE = \"{}\";\n\n",
        wasm_mod
    ));

    for f in &m.functions {
        out.push_str(&generate_java_interface(f));
    }

    out.push_str("  public static Builder builder() {\n");
    out.push_str("    return new Builder();\n");
    out.push_str("  }\n\n");

    out.push_str("  public static class Builder {\n\n");
    for f in &m.functions {
        let handler_type = format!("{}Handler", f.name.to_upper_camel_case());
        let field = f.name.to_lower_camel_case();
        out.push_str(&format!("    private {} {};\n", handler_type, field));
    }
    out.push_str("\n");

    for f in &m.functions {
        let handler_type = format!("{}Handler", f.name.to_upper_camel_case());
        let field = f.name.to_lower_camel_case();
        let method = format!("with{}", f.name.to_upper_camel_case());
        out.push_str(&format!(
            "    public Builder {}({} handler) {{\n      this.{} = handler;\n      return this;\n    }}\n\n",
            method, handler_type, field
        ));
    }

    out.push_str("    public HostFunction[] build() {\n");
    out.push_str("      List<HostFunction> functions = new ArrayList<>();\n");
    for f in &m.functions {
        let field = f.name.to_lower_camel_case();
        out.push_str(&format!(
            "      if ({} != null) {{\n        functions.add(create{}Function());\n      }}\n",
            field,
            f.name.to_upper_camel_case()
        ));
    }
    out.push_str("      return functions.toArray(new HostFunction[0]);\n");
    out.push_str("    }\n\n");

    for f in &m.functions {
        out.push_str(&generate_java_host_function(f, wasm_mod));
    }

    out.push_str("  }\n");
    out.push_str("}\n");

    out
}

fn generate_java_interface(f: &Function) -> String {
    let iface_name = format!("{}Handler", f.name.to_upper_camel_case());
    let ret = java_return_type(f.returns.as_deref());
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{} {}", java_type(&p.ty), p.name.to_lower_camel_case()))
        .collect();

    format!(
        "  @FunctionalInterface\n  public interface {} {{\n    {} handle({});\n  }}\n\n",
        iface_name,
        ret,
        params.join(", ")
    )
}

fn generate_java_host_function(f: &Function, wasm_mod: &str) -> String {
    let method_name = format!("create{}Function", f.name.to_upper_camel_case());
    let field = f.name.to_lower_camel_case();
    let has_string_return =
        f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes");

    let mut wasm_params = Vec::new();
    for p in &f.params {
        match p.ty.as_str() {
            "string" | "bytes" => {
                wasm_params.push("ValueType.I32");
                wasm_params.push("ValueType.I32");
            }
            "int" => wasm_params.push("ValueType.I32"),
            "float" => wasm_params.push("ValueType.F64"),
            _ => wasm_params.push("ValueType.I32"),
        }
    }
    if has_string_return {
        wasm_params.push("ValueType.I32");
        wasm_params.push("ValueType.I32");
    }

    let wasm_returns = match f.returns.as_deref() {
        Some("string") | Some("bytes") | Some("int") => vec!["ValueType.I32"],
        Some("float") => vec!["ValueType.F64"],
        None => vec![],
        _ => vec!["ValueType.I32"],
    };

    let mut out = String::new();
    out.push_str(&format!("    private HostFunction {}() {{\n", method_name));
    out.push_str(&format!(
        "      return new HostFunction(\n          MODULE,\n          \"{}\",\n          List.of({}),\n          List.of({}),\n          (Instance instance, long... args) -> {{\n",
        f.name,
        wasm_params.join(", "),
        wasm_returns.join(", ")
    ));

    out.push_str("            Memory memory = instance.memory();\n");
    let mut arg_idx = 0;
    for p in &f.params {
        let java_name = p.name.to_lower_camel_case();
        match p.ty.as_str() {
            "string" => {
                out.push_str(&format!(
                    "            int {name}Ptr = Math.toIntExact(args[{i}]);\n            int {name}Len = Math.toIntExact(args[{j}]);\n            String {name} = memory.readString({name}Ptr, {name}Len, StandardCharsets.UTF_8);\n",
                    name = java_name, i = arg_idx, j = arg_idx + 1
                ));
                arg_idx += 2;
            }
            "bytes" => {
                out.push_str(&format!(
                    "            int {name}Ptr = Math.toIntExact(args[{i}]);\n            int {name}Len = Math.toIntExact(args[{j}]);\n            byte[] {name} = memory.readBytes({name}Ptr, {name}Len);\n",
                    name = java_name, i = arg_idx, j = arg_idx + 1
                ));
                arg_idx += 2;
            }
            "int" => {
                out.push_str(&format!(
                    "            int {} = Math.toIntExact(args[{}]);\n",
                    java_name, arg_idx
                ));
                arg_idx += 1;
            }
            "float" => {
                out.push_str(&format!(
                    "            double {} = Double.longBitsToDouble(args[{}]);\n",
                    java_name, arg_idx
                ));
                arg_idx += 1;
            }
            _ => { arg_idx += 1; }
        }
    }

    if has_string_return {
        out.push_str(&format!(
            "            int resultPtr = Math.toIntExact(args[{}]);\n            int resultMaxLen = Math.toIntExact(args[{}]);\n",
            arg_idx, arg_idx + 1
        ));
    }

    let call_args: Vec<String> = f.params.iter().map(|p| p.name.to_lower_camel_case()).collect();
    let call_expr = format!("{}.handle({})", field, call_args.join(", "));

    match f.returns.as_deref() {
        Some("string") => {
            out.push_str(&format!("            String result = {};\n", call_expr));
            out.push_str("            byte[] resultBytes = result.getBytes(StandardCharsets.UTF_8);\n");
            out.push_str("            if (resultBytes.length > resultMaxLen) {\n");
            out.push_str("              return new long[] { -2 };\n");
            out.push_str("            }\n");
            out.push_str("            memory.write(resultPtr, resultBytes);\n");
            out.push_str("            return new long[] { resultBytes.length };\n");
        }
        Some("int") => {
            out.push_str(&format!("            int result = {};\n", call_expr));
            out.push_str("            return new long[] { result };\n");
        }
        None => {
            out.push_str(&format!("            {};\n", call_expr));
            out.push_str("            return null;\n");
        }
        _ => {
            out.push_str(&format!("            return new long[] {{ {} }};\n", call_expr));
        }
    }

    out.push_str("          });\n");
    out.push_str("    }\n\n");

    out
}

fn java_type(ty: &str) -> &'static str {
    match ty {
        "string" => "String",
        "int" => "int",
        "float" => "double",
        "bytes" => "byte[]",
        _ => "String",
    }
}

fn java_return_type(ty: Option<&str>) -> &'static str {
    match ty {
        Some("string") => "String",
        Some("int") => "int",
        Some("float") => "double",
        Some("bytes") => "byte[]",
        None => "void",
        _ => "String",
    }
}
