use askama::Template;
use heck::{ToLowerCamelCase, ToUpperCamelCase};
use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
pub struct Manifest {
    pub extension: Extension,
    #[serde(default)]
    pub functions: Vec<Function>,
}

#[derive(Deserialize)]
pub struct Extension {
    pub name: String,
    pub wasm_module: Option<String>,
    #[serde(default)]
    pub prewarm: Vec<String>,
}

#[derive(Deserialize)]
pub struct Function {
    pub name: String,
    #[serde(default)]
    pub params: Vec<Param>,
    #[serde(default)]
    pub returns: Option<String>,
    #[serde(default)]
    pub r#async: bool,
}

#[derive(Deserialize)]
pub struct Param {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: String,
}

pub fn parse_manifest(path: &Path) -> Manifest {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    toml::from_str(&content).unwrap_or_else(|e| panic!("Failed to parse {}: {}", path.display(), e))
}

/// Call from your extension crate's build.rs.
/// Reads extension.toml from the crate root and writes generated Rust to OUT_DIR.
///
/// ```rust,ignore
/// // build.rs
/// fn main() {
///     boomslang_hostgen::generate_rust("extension.toml");
/// }
/// ```
pub fn generate_rust(manifest_path: &str) {
    let manifest_path = Path::new(manifest_path);
    let manifest = parse_manifest(manifest_path);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set (are you in a build.rs?)");
    let filename = format!("ext_{}.rs", manifest.extension.name);
    let code = generate_rust_code(&manifest);
    fs::write(Path::new(&out_dir).join(&filename), code).unwrap();

    println!("cargo:rerun-if-changed={}", manifest_path.display());
}

/// Generate Java host function bindings to a directory.
pub fn generate_java(manifest_path: &str, out_dir: &str, package: &str) {
    let manifest = parse_manifest(Path::new(manifest_path));
    let package_dir = Path::new(out_dir).join(package.replace('.', "/"));
    fs::create_dir_all(&package_dir).unwrap();
    let code = generate_java_code(&manifest, package);
    let classname = format!(
        "{}HostFunctions",
        manifest.extension.name.to_upper_camel_case()
    );
    fs::write(package_dir.join(format!("{}.java", classname)), code).unwrap();
}

// ── Rust codegen ──────────────────────────────────────────────

pub fn generate_rust_code(m: &Manifest) -> String {
    let mod_name = &m.extension.name;
    let wasm_mod = m.extension.wasm_module.as_deref().unwrap_or(mod_name);

    let mut out = String::new();
    out.push_str("use pyo3::prelude::*;\n\n");

    // WASM import declarations
    if !m.functions.is_empty() {
        out.push_str(&format!("#[link(wasm_import_module = \"{}\")]\n", wasm_mod));
        out.push_str("unsafe extern \"C\" {\n");
        for f in &m.functions {
            out.push_str(&format!("    fn {}(\n", wasm_import_name(f)));
            for p in &f.params {
                for (wn, wt) in wasm_params(&p.name, &p.ty) {
                    out.push_str(&format!("        {}: {},\n", wn, wt));
                }
            }
            if !f.r#async
                && (f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes"))
            {
                out.push_str("        result_ptr: *mut u8,\n");
                out.push_str("        result_max_len: i32,\n");
            }
            let ret = wasm_return_type(f);
            out.push_str(&format!("    ) -> {};\n", ret));
        }
        out.push_str("}\n\n");
    }

    out.push_str("const MAX_RESULT: i32 = 1024 * 1024;\n\n");

    // PyO3 wrapper functions
    for f in &m.functions {
        out.push_str(&generate_rust_pyo3_wrapper(f));
        out.push_str("\n");
    }

    // Forward-declare the PyInit function generated by #[pymodule]
    let py_mod_name = format!("_{}", mod_name);
    out.push_str(&format!(
        "unsafe extern \"C\" {{\n    #[allow(non_snake_case)]\n    fn PyInit_{}() -> *mut pyo3::ffi::PyObject;\n}}\n\n",
        py_mod_name
    ));

    // Module registration
    out.push_str(&format!(
        "pub fn register() {{\n    unsafe {{\n        pyo3::ffi::PyImport_AppendInittab(\n            b\"{}\\0\".as_ptr() as *const i8,\n            Some(PyInit_{}),\n        );\n    }}\n}}\n\n",
        py_mod_name, py_mod_name
    ));

    out.push_str(&format!(
        "pub fn prewarm(py: Python) {{\n    let modules = {:?};\n    for name in modules {{\n        match py.import(name) {{\n            Ok(_) => eprintln!(\"[prewarm] OK: {{}}\", name),\n            Err(e) => eprintln!(\"[prewarm] FAILED: {{}} - {{:?}}\", name, e),\n        }}\n    }}\n}}\n\n",
        m.extension.prewarm
    ));

    // #[pymodule]
    out.push_str(&format!(
        "#[pymodule]\nfn {}(m: &Bound<'_, PyModule>) -> PyResult<()> {{\n",
        py_mod_name
    ));
    for f in &m.functions {
        out.push_str(&format!(
            "    m.add_function(wrap_pyfunction!(py_{}, m)?)?;\n",
            f.name
        ));
    }
    out.push_str("    Ok(())\n}\n");

    out
}

fn generate_rust_pyo3_wrapper(f: &Function) -> String {
    if f.r#async {
        return generate_rust_async_pyo3_wrapper(f);
    }

    let mut out = String::new();

    out.push_str(&format!("#[pyfunction]\n#[pyo3(name = \"{}\")]\n", f.name));
    let ret_type = match f.returns.as_deref() {
        Some("string") => "PyResult<String>",
        Some("int") => "PyResult<i32>",
        Some("float") => "PyResult<f64>",
        Some("bytes") => "PyResult<Vec<u8>>",
        None => "PyResult<()>",
        _ => "PyResult<String>",
    };
    out.push_str(&format!("fn py_{}(", f.name));
    let py_params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", &p.name, rust_py_type(&p.ty)))
        .collect();
    out.push_str(&py_params.join(", "));
    out.push_str(&format!(") -> {} {{\n", ret_type));
    out.push_str("    unsafe {\n");

    for p in &f.params {
        if p.ty == "string" {
            out.push_str(&format!(
                "        let {name}_bytes = {name}.as_bytes();\n",
                name = p.name
            ));
        } else if p.ty == "bytes" {
            out.push_str(&format!(
                "        let {name}_bytes = {name};\n",
                name = p.name
            ));
        }
    }

    if f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes") {
        out.push_str("        let mut result_buf = vec![0u8; MAX_RESULT as usize];\n");
    }

    if f.returns.is_some() {
        out.push_str(&format!("        let ret = {}(\n", wasm_import_name(f)));
    } else {
        out.push_str(&format!("        {}(\n", wasm_import_name(f)));
    }
    for p in &f.params {
        match p.ty.as_str() {
            "string" | "bytes" => {
                out.push_str(&format!(
                    "            {name}_bytes.as_ptr(),\n            {name}_bytes.len() as i32,\n",
                    name = p.name
                ));
            }
            "int" | "float" => {
                out.push_str(&format!("            {},\n", p.name));
            }
            _ => {}
        }
    }
    if f.returns.as_deref() == Some("string") || f.returns.as_deref() == Some("bytes") {
        out.push_str("            result_buf.as_mut_ptr(),\n");
        out.push_str("            MAX_RESULT,\n");
    }
    out.push_str("        );\n");

    match f.returns.as_deref() {
        Some("string") => {
            out.push_str("        if ret < 0 {\n");
            out.push_str("            return Err(PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(\"host call failed\"));\n");
            out.push_str("        }\n");
            out.push_str(
                "        Ok(String::from_utf8_lossy(&result_buf[..ret as usize]).into_owned())\n",
            );
        }
        Some("bytes") => {
            out.push_str("        if ret < 0 {\n");
            out.push_str("            return Err(PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(\"host call failed\"));\n");
            out.push_str("        }\n");
            out.push_str("        Ok(result_buf[..ret as usize].to_vec())\n");
        }
        Some("int") => out.push_str("        Ok(ret)\n"),
        None => out.push_str("        Ok(())\n"),
        _ => out.push_str("        Ok(ret)\n"),
    }

    out.push_str("    }\n}\n");
    out
}

fn generate_rust_async_pyo3_wrapper(f: &Function) -> String {
    validate_async_function(f);
    let mut out = String::new();
    out.push_str(&format!("#[pyfunction]\n#[pyo3(name = \"{}\")]\n", f.name));
    out.push_str(&format!("fn py_{}(py: Python", f.name));
    for p in &f.params {
        out.push_str(&format!(", {}: {}", p.name, rust_py_type(&p.ty)));
    }
    out.push_str(") -> PyResult<Py<PyAny>> {\n");
    out.push_str("    unsafe {\n");
    for p in &f.params {
        if p.ty == "string" {
            out.push_str(&format!(
                "        let {name}_bytes = {name}.as_bytes();\n",
                name = p.name
            ));
        } else if p.ty == "bytes" {
            out.push_str(&format!(
                "        let {name}_bytes = {name};\n",
                name = p.name
            ));
        }
    }
    out.push_str(&format!("        let token = {}(\n", wasm_import_name(f)));
    for p in &f.params {
        match p.ty.as_str() {
            "string" | "bytes" => {
                out.push_str(&format!(
                    "            {name}_bytes.as_ptr(),\n            {name}_bytes.len() as i32,\n",
                    name = p.name
                ));
            }
            "int" | "float" => {
                out.push_str(&format!("            {},\n", p.name));
            }
            _ => {}
        }
    }
    out.push_str("        );\n");
    // Defense in depth: tokens are always positive, so a negative return means the host could not
    // even register the call. Fail loudly here rather than handing a bogus token to the event loop
    // (boomslang_host.asyncio also rejects non-positive tokens).
    out.push_str("        if token < 0 {\n");
    out.push_str("            return Err(PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(\"async host call failed\"));\n");
    out.push_str("        }\n");
    out.push_str("        let asyncio = py.import(\"boomslang_host.asyncio\")?;\n");
    out.push_str("        let from_host_token = asyncio.getattr(\"from_host_token\")?;\n");
    out.push_str("        let future = from_host_token.call1((token,))?;\n");
    out.push_str("        Ok(future.unbind())\n");
    out.push_str("    }\n}\n");
    out
}

fn validate_async_function(f: &Function) {
    if f.returns.as_deref() != Some("string") {
        panic!("Async function '{}' must currently return string", f.name);
    }
}

fn wasm_import_name(f: &Function) -> String {
    f.name.clone()
}

fn wasm_params(name: &str, ty: &str) -> Vec<(String, &'static str)> {
    match ty {
        "string" | "bytes" => vec![
            (format!("{}_ptr", name), "*const u8"),
            (format!("{}_len", name), "i32"),
        ],
        "int" => vec![(name.to_string(), "i32")],
        "float" => vec![(name.to_string(), "f64")],
        _ => vec![(name.to_string(), "i32")],
    }
}

fn wasm_return_type(f: &Function) -> &'static str {
    if f.r#async {
        validate_async_function(f);
        return "i64";
    }
    match f.returns.as_deref() {
        Some("string") | Some("bytes") | Some("int") => "i32",
        Some("float") => "f64",
        None => "()",
        _ => "i32",
    }
}

fn rust_py_type(ty: &str) -> &'static str {
    match ty {
        "string" => "&str",
        "int" => "i32",
        "float" => "f64",
        "bytes" => "&[u8]",
        _ => "&str",
    }
}

// ── Java codegen ──────────────────────────────────────────────

#[derive(Template)]
#[template(path = "java_host_functions.java", escape = "none")]
struct JavaHostFunctionsTemplate {
    package: String,
    class_name: String,
    extension_name: String,
    wasm_module: String,
    functions: Vec<JavaFunctionTemplate>,
}

struct JavaFunctionTemplate {
    name: String,
    upper_name: String,
    field: String,
    handler_type: String,
    with_method: String,
    return_type: String,
    interface_params: String,
    wasm_params: String,
    wasm_returns: String,
    param_reads: String,
    return_handling: String,
    error_handling: &'static str,
    #[allow(dead_code)]
    is_async: bool,
    needs_memory: bool,
}

pub fn generate_java_code(m: &Manifest, package: &str) -> String {
    let ext_name = &m.extension.name;
    let template = JavaHostFunctionsTemplate {
        package: package.to_string(),
        class_name: format!("{}HostFunctions", ext_name.to_upper_camel_case()),
        extension_name: ext_name.to_string(),
        wasm_module: m
            .extension
            .wasm_module
            .as_deref()
            .unwrap_or(ext_name)
            .to_string(),
        functions: m.functions.iter().map(java_function_template).collect(),
    };

    template
        .render()
        .expect("failed to render Java host functions template")
}

fn java_function_template(f: &Function) -> JavaFunctionTemplate {
    let field = f.name.to_lower_camel_case();
    JavaFunctionTemplate {
        name: f.name.clone(),
        upper_name: f.name.to_upper_camel_case(),
        field: field.clone(),
        handler_type: format!("{}Handler", f.name.to_upper_camel_case()),
        with_method: format!("with{}", f.name.to_upper_camel_case()),
        return_type: java_handler_return_type(f),
        interface_params: java_interface_params(f),
        wasm_params: java_wasm_params(f).join(", "),
        wasm_returns: java_wasm_returns(f).join(", "),
        param_reads: java_param_reads(f),
        return_handling: java_return_handling(f, &field),
        error_handling: java_error_handling(f),
        is_async: f.r#async,
        needs_memory: java_needs_memory(f),
    }
}

/// Whether the generated host function body touches WASM linear memory: true when it reads any
/// string/bytes argument, or writes a string/bytes result back into a caller-provided buffer.
/// Functions with only scalar params and no buffer return (e.g. `add`) must NOT declare the
/// `Memory` local, otherwise error-prone's UnusedLocalVariable check fails downstream.
fn java_needs_memory(f: &Function) -> bool {
    let reads_buffer = f
        .params
        .iter()
        .any(|p| p.ty == "string" || p.ty == "bytes");
    let writes_buffer = !f.r#async && is_buffer_return(f.returns.as_deref());
    reads_buffer || writes_buffer
}

fn java_interface_params(f: &Function) -> String {
    f.params
        .iter()
        .map(|p| format!("{} {}", java_type(&p.ty), p.name.to_lower_camel_case()))
        .collect::<Vec<_>>()
        .join(", ")
}

fn java_wasm_params(f: &Function) -> Vec<&'static str> {
    let mut params = Vec::new();
    for p in &f.params {
        match p.ty.as_str() {
            "string" | "bytes" => {
                params.push("ValueType.I32");
                params.push("ValueType.I32");
            }
            "int" => params.push("ValueType.I32"),
            "float" => params.push("ValueType.F64"),
            other => panic!("Unsupported Java parameter type '{}' for {}", other, f.name),
        }
    }
    if !f.r#async && is_buffer_return(f.returns.as_deref()) {
        params.push("ValueType.I32");
        params.push("ValueType.I32");
    }
    params
}

fn java_wasm_returns(f: &Function) -> Vec<&'static str> {
    if f.r#async {
        validate_async_function(f);
        return vec!["ValueType.I64"];
    }
    match f.returns.as_deref() {
        Some("string") | Some("bytes") | Some("int") => vec!["ValueType.I32"],
        Some("float") => vec!["ValueType.F64"],
        None => vec![],
        Some(other) => panic!("Unsupported Java return type '{}' for {}", other, f.name),
    }
}

fn java_param_reads(f: &Function) -> String {
    let mut out = String::new();
    let mut arg_idx = 0;
    for (param_idx, p) in f.params.iter().enumerate() {
        let java_name = format!("param{}", param_idx);
        match p.ty.as_str() {
            "string" => {
                out.push_str(&format!(
                    "            int {name}Ptr = Math.toIntExact(wasmArgs[{i}]);\n            int {name}Len = Math.toIntExact(wasmArgs[{j}]);\n            String {name} = memory.readString({name}Ptr, {name}Len, StandardCharsets.UTF_8);\n",
                    name = java_name,
                    i = arg_idx,
                    j = arg_idx + 1
                ));
                arg_idx += 2;
            }
            "bytes" => {
                out.push_str(&format!(
                    "            int {name}Ptr = Math.toIntExact(wasmArgs[{i}]);\n            int {name}Len = Math.toIntExact(wasmArgs[{j}]);\n            byte[] {name} = memory.readBytes({name}Ptr, {name}Len);\n",
                    name = java_name,
                    i = arg_idx,
                    j = arg_idx + 1
                ));
                arg_idx += 2;
            }
            "int" => {
                out.push_str(&format!(
                    "            int {} = Math.toIntExact(wasmArgs[{}]);\n",
                    java_name, arg_idx
                ));
                arg_idx += 1;
            }
            "float" => {
                out.push_str(&format!(
                    "            double {} = Double.longBitsToDouble(wasmArgs[{}]);\n",
                    java_name, arg_idx
                ));
                arg_idx += 1;
            }
            other => panic!("Unsupported Java parameter type '{}' for {}", other, f.name),
        }
    }

    if !f.r#async && is_buffer_return(f.returns.as_deref()) {
        out.push_str(&format!(
            "            int resultPtr = Math.toIntExact(wasmArgs[{}]);\n            int resultMaxLen = Math.toIntExact(wasmArgs[{}]);\n",
            arg_idx,
            arg_idx + 1
        ));
    }

    out
}

fn java_return_handling(f: &Function, field: &str) -> String {
    let call_expr = java_handler_call(f, field);
    if f.r#async {
        validate_async_function(f);
        return format!(
            "              if (asyncRegistry == null) {{\n                throw new IllegalStateException(\"AsyncHostRegistry is required for async host function \" + MODULE + \"::{name}\");\n              }}\n              CompletionStage<String> stage = {call_expr};\n              if (stage == null) {{\n                throw new IllegalStateException(\"Host function returned null: \" + MODULE + \"::{name}\");\n              }}\n              return new long[] {{ asyncRegistry.start(stage) }};",
            call_expr = call_expr,
            name = f.name
        );
    }
    match f.returns.as_deref() {
        Some("string") => format!(
            "              String result = {call_expr};\n              if (result == null) {{\n                throw new IllegalStateException(\"Host function returned null: \" + MODULE + \"::{name}\");\n              }}\n              byte[] resultBytes = result.getBytes(StandardCharsets.UTF_8);\n              if (resultBytes.length > resultMaxLen) {{\n                return new long[] {{ -2 }};\n              }}\n              memory.write(resultPtr, resultBytes);\n              return new long[] {{ resultBytes.length }};",
            call_expr = call_expr,
            name = f.name
        ),
        Some("bytes") => format!(
            "              byte[] resultBytes = {call_expr};\n              if (resultBytes == null) {{\n                throw new IllegalStateException(\"Host function returned null: \" + MODULE + \"::{name}\");\n              }}\n              if (resultBytes.length > resultMaxLen) {{\n                return new long[] {{ -2 }};\n              }}\n              memory.write(resultPtr, resultBytes);\n              return new long[] {{ resultBytes.length }};",
            call_expr = call_expr,
            name = f.name
        ),
        Some("int") => format!(
            "              int result = {};\n              return new long[] {{ result }};",
            call_expr
        ),
        Some("float") => format!(
            "              double result = {};\n              return new long[] {{ Double.doubleToRawLongBits(result) }};",
            call_expr
        ),
        None => format!(
            "              {};\n              return null;",
            call_expr
        ),
        Some(other) => panic!("Unsupported Java return type '{}' for {}", other, f.name),
    }
}

fn java_handler_call(f: &Function, field: &str) -> String {
    let call_args = f
        .params
        .iter()
        .enumerate()
        .map(|(idx, _)| format!("param{}", idx))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{}.handle({})", field, call_args)
}

fn java_error_handling(f: &Function) -> &'static str {
    if f.r#async {
        // Deliver the failure through the normal completion path so the awaiting coroutine raises,
        // instead of returning a sentinel token the event loop would wait on forever. Fall back to
        // -1 only when there is no registry to record the failure (the client rejects token <= 0).
        "              if (asyncRegistry == null) {\n                return new long[] { -1 };\n              }\n              return new long[] { asyncRegistry.startFailed(e) };"
    } else if is_buffer_return(f.returns.as_deref()) {
        "              return new long[] { -1 };"
    } else {
        "              throw e;"
    }
}

fn is_buffer_return(ty: Option<&str>) -> bool {
    matches!(ty, Some("string") | Some("bytes"))
}

fn java_type(ty: &str) -> &'static str {
    match ty {
        "string" => "String",
        "int" => "int",
        "float" => "double",
        "bytes" => "byte[]",
        other => panic!("Unsupported Java type '{}'", other),
    }
}

fn java_handler_return_type(f: &Function) -> String {
    if f.r#async {
        validate_async_function(f);
        "CompletionStage<String>".to_string()
    } else {
        java_return_type(f.returns.as_deref()).to_string()
    }
}

fn java_return_type(ty: Option<&str>) -> &'static str {
    match ty {
        Some("string") => "String",
        Some("int") => "int",
        Some("float") => "double",
        Some("bytes") => "byte[]",
        None => "void",
        Some(other) => panic!("Unsupported Java return type '{}'", other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn async_manifest() -> Manifest {
        toml::from_str(
            r#"
[extension]
name = "demo_async"
wasm_module = "demo"

[[functions]]
name = "lookup"
async = true
params = [
  { name = "request", type = "string" },
  { name = "count", type = "int" },
]
returns = "string"

[[functions]]
name = "echo"
params = [{ name = "request", type = "string" }]
returns = "string"
"#,
        )
        .unwrap()
    }

    #[test]
    fn it_generates_async_java_handlers_with_typed_args() {
        let code = generate_java_code(&async_manifest(), "com.example");

        assert!(code.contains("import com.hubspot.boomslang.AsyncHostRegistry;"));
        assert!(code.contains("CompletionStage<String> handle(String request, int count);"));
        assert!(code.contains("public Builder withAsyncRegistry(AsyncHostRegistry asyncRegistry)"));
        assert!(code.contains("functions.add(createLookupFunction());"));
        assert!(code.contains("int param1 = Math.toIntExact(wasmArgs[2]);"));
        assert!(code.contains("CompletionStage<String> stage = lookup.handle(param0, param1);"));
        assert!(code.contains("return new long[] { asyncRegistry.start(stage) };"));
        assert!(code.contains("return new long[] { asyncRegistry.startFailed(e) };"));
        assert!(code.contains("functions.add(createEchoFunction());"));
    }

    #[test]
    fn it_generates_async_rust_wrapper_using_boomslang_asyncio() {
        let code = generate_rust_code(&async_manifest());

        assert!(code.contains(
            "fn py_lookup(py: Python, request: &str, count: i32) -> PyResult<Py<PyAny>>"
        ));
        assert!(code.contains("py.import(\"boomslang_host.asyncio\")?"));
        assert!(code.contains("let token = lookup("));
        assert!(code.contains("if token < 0"));
        assert!(code.contains("request_bytes.as_ptr()"));
        assert!(code.contains("count,"));
        assert!(code.contains("from_host_token.call1((token,))?"));
        assert!(code.contains("fn echo("));
        assert!(code.contains("fn lookup(\n"));
    }
}
