// Generated by boomslang-hostgen. Do not edit by hand.
use anyhow::{bail, Context, Result};
use std::collections::{HashMap, HashSet, VecDeque};
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::{Arc, Condvar, Mutex, MutexGuard};
use std::thread;
use std::time::Duration;
use wasmtime::{Caller, FuncType, Linker, Memory, Val, ValType};

#[derive(Clone, Default)]
pub struct {{ struct_name }} {
{%- for function in functions %}
    {{ function.field }}: Option<{{ function.arc_handler_type }}>,
{%- endfor %}
}

#[derive(Default)]
pub struct {{ builder_name }} {
{%- for function in functions %}
    {{ function.field }}: Option<{{ function.arc_handler_type }}>,
{%- endfor %}
}

impl {{ struct_name }} {
    pub const EXTENSION_NAME: &'static str = {{ extension_name }};
    pub const MODULE: &'static str = {{ wasm_module }};

    pub fn builder() -> {{ builder_name }} {
        {{ builder_name }}::default()
    }

    pub fn register<T: Send + 'static>(&self, linker: &mut Linker<T>) -> Result<Vec<&'static str>> {
{%- for function in functions %}
        self.{{ function.register_method }}(linker)?;
{%- endfor %}
        Ok({{ imports }})
    }

{% for function in functions %}
    fn {{ function.register_method }}<T: Send + 'static>(&self, linker: &mut Linker<T>) -> Result<()> {
        let handler = self.{{ function.field }}.clone();
        let ty = FuncType::new(
            linker.engine(),
            {{ function.wasm_params }},
            {{ function.wasm_returns }},
        );
        linker.func_new(
            Self::MODULE,
            {{ function.import_name }},
            ty,
            move |mut caller: Caller<'_, T>, params: &[Val], {{ function.results_name }}: &mut [Val]| {
                let result = (|| -> Result<()> {
                    let Some(handler) = handler.as_ref() else {
                        bail!("No handler registered for host function {}::{{ function.name }}", Self::MODULE);
                    };
{% if function.needs_memory %}
                    let memory = caller_memory(&mut caller)?;
{% endif %}{{ function.param_reads }}{{ function.return_handling }}                    Ok(())
                })();
{{ function.error_handling }}            },
        )?;
        Ok(())
    }

{% endfor %}
}

impl {{ builder_name }} {
{% for function in functions %}
    pub fn {{ function.with_method }}<F>(mut self, handler: F) -> Self
    where
        F: {{ function.fn_bound }} + Send + Sync + 'static,
    {
        self.{{ function.field }} = Some(Arc::new(handler));
        self
    }

{% endfor %}
    pub fn build(self) -> {{ struct_name }} {
        {{ struct_name }} {
{%- for function in functions %}
            {{ function.field }}: self.{{ function.field }},
{%- endfor %}
        }
    }
}

#[derive(Clone, Default)]
pub struct AsyncHostRegistry {
    inner: Arc<AsyncHostRegistryInner>,
}

#[derive(Default)]
struct AsyncHostRegistryInner {
    next_token: AtomicI64,
    state: Mutex<AsyncHostRegistryState>,
    ready: Condvar,
}

type AsyncTokenHandler = Arc<dyn Fn(String, String) -> Result<i64> + Send + Sync>;

#[derive(Default)]
struct AsyncHostRegistryState {
    handlers: HashMap<String, AsyncTokenHandler>,
    pending: HashSet<i64>,
    completed: VecDeque<AsyncCompletion>,
    ready: HashMap<i64, AsyncCompletion>,
    canceled: HashSet<i64>,
}

#[derive(Clone)]
struct AsyncCompletion {
    token: i64,
    ok: bool,
    value: Vec<u8>,
}

#[allow(dead_code)]
impl AsyncHostRegistry {
    pub const PROTOCOL_VERSION: i32 = 1;
    pub const PROTOCOL: &'static str = "__async_protocol__";
    pub const START: &'static str = "__async_start__";
    pub const POLL: &'static str = "__async_poll__";
    pub const RESULT: &'static str = "__async_result__";
    pub const CANCEL: &'static str = "__async_cancel__";

    pub fn is_control_call(name: &str) -> bool {
        matches!(
            name,
            Self::PROTOCOL | Self::START | Self::POLL | Self::RESULT | Self::CANCEL
        )
    }

    pub fn handle_call_or<F>(&self, name: String, args: String, fallback: F) -> Result<String>
    where
        F: FnOnce(String, String) -> Result<String>,
    {
        if let Some(result) = self.handle_control_call(&name, &args)? {
            return Ok(result);
        }
        fallback(name, args)
    }

    pub fn handle_control_call(&self, name: &str, args: &str) -> Result<Option<String>> {
        match name {
            Self::PROTOCOL => Ok(Some(Self::PROTOCOL_VERSION.to_string())),
            Self::START => Ok(Some(self.start_named(args)?)),
            Self::POLL => {
                let timeout_ms = args.trim().parse::<i64>().context("invalid async poll timeout")?;
                Ok(Some(self.poll(timeout_ms)?))
            }
            Self::RESULT => {
                let token = args.trim().parse::<i64>().context("invalid async token")?;
                Ok(Some(self.result(token)?))
            }
            Self::CANCEL => {
                let token = args.trim().parse::<i64>().context("invalid async token")?;
                self.cancel(token)?;
                Ok(Some(String::new()))
            }
            _ => Ok(None),
        }
    }

    pub fn register_token_handler<F>(&self, name: impl Into<String>, handler: F) -> Result<()>
    where
        F: Fn(String, String) -> Result<i64> + Send + Sync + 'static,
    {
        self.lock_state()?.handlers.insert(name.into(), Arc::new(handler));
        Ok(())
    }

    pub fn register_blocking_handler<F>(&self, name: impl Into<String>, handler: F) -> Result<()>
    where
        F: Fn(String, String) -> Result<String> + Send + Sync + 'static,
    {
        let handler = Arc::new(handler);
        let registry = self.clone();
        self.register_token_handler(name, move |name, args| {
            let handler = Arc::clone(&handler);
            registry.start_blocking(move || handler(name, args))
        })
    }

    pub fn start_completed(&self, value: impl Into<String>) -> Result<i64> {
        self.complete_new(true, value.into().into_bytes())
    }

    pub fn start_failed(&self, error: impl ToString) -> Result<i64> {
        self.complete_new(false, error.to_string().into_bytes())
    }

    pub fn start_blocking<F>(&self, work: F) -> Result<i64>
    where
        F: FnOnce() -> Result<String> + Send + 'static,
    {
        let token = self.allocate_pending_token()?;
        let registry = self.clone();
        thread::spawn(move || {
            let (ok, value) = match work() {
                Ok(value) => (true, value.into_bytes()),
                Err(error) => (false, format!("{error:#}").into_bytes()),
            };
            if let Err(error) = registry.complete_existing(token, ok, value) {
                eprintln!("async host completion failed for token {token}: {error:#}");
            }
        });
        Ok(token)
    }

    pub fn cancel(&self, token: i64) -> Result<()> {
        let mut state = self.lock_state()?;
        if state.pending.remove(&token) {
            state.canceled.insert(token);
        }
        state.completed.retain(|completion| completion.token != token);
        state.ready.remove(&token);
        Ok(())
    }

    fn start_named(&self, args: &str) -> Result<String> {
        let (name, payload) = args.split_once('\n').unwrap_or((args, ""));
        let handler = self.lock_state()?.handlers.get(name).cloned();
        let token = match handler {
            Some(handler) => match handler(name.to_string(), payload.to_string()) {
                Ok(token) => token,
                Err(error) => self.start_failed(format!("{error:#}"))?,
            },
            None => self.start_failed(format!("No async handler registered for: {name}"))?,
        };
        Ok(token.to_string())
    }

    fn poll(&self, timeout_ms: i64) -> Result<String> {
        let mut state = self.lock_state()?;
        if timeout_ms < 0 {
            while state.completed.is_empty() {
                state = self
                    .inner
                    .ready
                    .wait(state)
                    .map_err(|_| anyhow::anyhow!("async registry lock poisoned"))?;
            }
        } else if timeout_ms > 0 && state.completed.is_empty() {
            let timeout = Duration::from_millis(timeout_ms as u64);
            let (guard, _) = self
                .inner
                .ready
                .wait_timeout_while(state, timeout, |state| state.completed.is_empty())
                .map_err(|_| anyhow::anyhow!("async registry lock poisoned"))?;
            state = guard;
        }

        let mut headers = String::new();
        while let Some(completion) = state.completed.pop_front() {
            headers.push_str(&format!(
                "{}\t{}\t{}\n",
                completion.token,
                if completion.ok { 1 } else { 0 },
                completion.value.len()
            ));
            state.ready.insert(completion.token, completion);
        }
        Ok(headers)
    }

    fn result(&self, token: i64) -> Result<String> {
        let completion = self.lock_state()?.ready.remove(&token);
        Ok(completion
            .map(|completion| base64_encode(&completion.value))
            .unwrap_or_default())
    }

    fn complete_new(&self, ok: bool, value: Vec<u8>) -> Result<i64> {
        let token = self.next_token();
        self.queue_completion(AsyncCompletion { token, ok, value })?;
        Ok(token)
    }

    fn allocate_pending_token(&self) -> Result<i64> {
        let token = self.next_token();
        self.lock_state()?.pending.insert(token);
        Ok(token)
    }

    fn complete_existing(&self, token: i64, ok: bool, value: Vec<u8>) -> Result<()> {
        let mut state = self.lock_state()?;
        let was_pending = state.pending.remove(&token);
        let was_canceled = state.canceled.remove(&token);
        if !was_pending || was_canceled {
            return Ok(());
        }
        state.completed.push_back(AsyncCompletion { token, ok, value });
        drop(state);
        self.inner.ready.notify_all();
        Ok(())
    }

    fn queue_completion(&self, completion: AsyncCompletion) -> Result<()> {
        self.lock_state()?.completed.push_back(completion);
        self.inner.ready.notify_all();
        Ok(())
    }

    fn next_token(&self) -> i64 {
        self.inner.next_token.fetch_add(1, Ordering::Relaxed) + 1
    }

    fn lock_state(&self) -> Result<MutexGuard<'_, AsyncHostRegistryState>> {
        self.inner
            .state
            .lock()
            .map_err(|_| anyhow::anyhow!("async registry lock poisoned"))
    }
}

#[allow(dead_code)]
fn base64_encode(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(((bytes.len() + 2) / 3) * 4);
    let mut index = 0;
    while index < bytes.len() {
        let b0 = bytes[index];
        let b1 = if index + 1 < bytes.len() {
            bytes[index + 1]
        } else {
            0
        };
        let b2 = if index + 2 < bytes.len() {
            bytes[index + 2]
        } else {
            0
        };
        out.push(TABLE[(b0 >> 2) as usize] as char);
        out.push(TABLE[(((b0 & 0b0000_0011) << 4) | (b1 >> 4)) as usize] as char);
        if index + 1 < bytes.len() {
            out.push(TABLE[(((b1 & 0b0000_1111) << 2) | (b2 >> 6)) as usize] as char);
        } else {
            out.push('=');
        }
        if index + 2 < bytes.len() {
            out.push(TABLE[(b2 & 0b0011_1111) as usize] as char);
        } else {
            out.push('=');
        }
        index += 3;
    }
    out
}

#[allow(dead_code)]
fn caller_memory<T>(caller: &mut Caller<'_, T>) -> Result<Memory> {
    caller
        .get_export("memory")
        .and_then(|export| export.into_memory())
        .context("host import needs the guest to export memory")
}

#[allow(dead_code)]
fn read_string<T>(caller: &Caller<'_, T>, memory: Memory, ptr: i32, len: i32) -> Result<String> {
    String::from_utf8(read_bytes(caller, memory, ptr, len)?)
        .context("host string argument is not valid UTF-8")
}

#[allow(dead_code)]
fn read_bytes<T>(caller: &Caller<'_, T>, memory: Memory, ptr: i32, len: i32) -> Result<Vec<u8>> {
    let ptr = usize::try_from(ptr).context("negative memory pointer")?;
    let len = usize::try_from(len).context("negative memory length")?;
    let end = ptr
        .checked_add(len)
        .context("memory range overflow while reading host argument")?;
    let data = memory.data(caller);
    let bytes = data
        .get(ptr..end)
        .with_context(|| format!("memory read out of bounds: {ptr}..{end}"))?;
    Ok(bytes.to_vec())
}

#[allow(dead_code)]
fn write_buffer_result<T>(
    caller: &mut Caller<'_, T>,
    memory: Memory,
    ptr: i32,
    max_len: i32,
    bytes: &[u8],
    results: &mut [Val],
) -> Result<()> {
    if max_len < 0 {
        bail!("negative result buffer length");
    }
    if bytes.len() > max_len as usize {
        results[0] = Val::I32(-2);
        return Ok(());
    }
    let ptr = usize::try_from(ptr).context("negative result buffer pointer")?;
    memory.write(caller, ptr, bytes)?;
    results[0] = Val::I32(bytes.len() as i32);
    Ok(())
}

#[allow(dead_code)]
fn expect_i32(params: &[Val], index: usize, name: &str) -> Result<i32> {
    match params.get(index) {
        Some(Val::I32(value)) => Ok(*value),
        other => bail!("expected i32 for {name} at arg {index}, got {other:?}"),
    }
}

#[allow(dead_code)]
fn expect_f64(params: &[Val], index: usize, name: &str) -> Result<f64> {
    match params.get(index) {
        Some(Val::F64(bits)) => Ok(f64::from_bits(*bits)),
        other => bail!("expected f64 for {name} at arg {index}, got {other:?}"),
    }
}
