[extension]
name = "boomslang_host"
wasm_module = "boomslang"
prewarm = ["_boomslang_host", "boomslang_host"]

[[functions]]
name = "call"
params = [
    { name = "name", type = "string" },
    { name = "args", type = "string" },
]
returns = "string"

[[functions]]
name = "log"
params = [
    { name = "level", type = "int" },
    { name = "message", type = "string" },
]
